# This is a template file. DO NOT commit actual secrets to git.
# Create the actual secrets using kubectl or your secret management system.

apiVersion: v1
kind: Secret
metadata:
  name: protobuddy-secrets
  namespace: protobuddy
type: Opaque
stringData:
  # Database
  postgres-password: "your-secure-postgres-password"
  database-url: "postgresql://protobuddy:your-secure-postgres-password@postgres-service:5432/protobuddy"

  # Redis
  redis-password: "your-secure-redis-password"
  redis-url: "redis://:your-secure-redis-password@redis-service:6379"

  # API Keys
  anthropic-api-key: "your-anthropic-api-key"
  apify-api-token: "your-apify-api-token"

  # Security
  jwt-secret: "your-jwt-secret"
  encryption-key: "your-32-character-encryption-key"

---
# ConfigMap for PostgreSQL initialization
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: protobuddy
data:
  01-schema.sql: |
    -- ProtoBuddy Database Schema will be inserted here during deployment
    -- This will be populated from backend/src/database/schema.sql